export type Region = 'North' | 'West' | 'South' | 'East' | 'North-East' | 'Central';

export type State = {
  slug: string; name: string; kind: 'State' | 'UT'; region: Region;
  tagline: string; bestSeason: string; daysNeeded: string; dailyBudget: string;
  airports: string; intro: string[]; quote: string; quoteBy: string;
};

const s = (
  slug: string, name: string, kind: 'State' | 'UT', region: Region, tagline: string,
  bestSeason: string, daysNeeded: string, dailyBudget: string, airports: string,
  intro: string[], quote: string, quoteBy: string,
): State => ({ slug, name, kind, region, tagline, bestSeason, daysNeeded, dailyBudget, airports, intro, quote, quoteBy });

export const STATES: State[] = [
  s('gujarat','Gujarat','State','West','Kutch, Gir, Statue of Unity','Nov – Feb','7 – 10','₹3,500','4 airports',
    ['The state runs from the Pakistani border at Kutch to the forested hills of the Dangs, and the distance between them is cultural as much as physical. In the north-west you sleep in a mud bhunga on salt flats that stretch flat to the horizon; six hours south you are in a Portuguese-era port town eating fish thali.',
     'Distances are long but the roads are among India\u2019s best, which makes Gujarat one of the few states where a self-drive loop genuinely beats the trains.'],
    'Come in the four months after Diwali. Everything you came for is open, and none of it is 44°C.','Nisha Thakkar · Gujarat editor'),
  s('rajasthan','Rajasthan','State','West','Jaipur, Udaipur, Jaisalmer','Oct – Mar','10 – 14','₹4,000','3 airports',
    ['Nine former kingdoms, each with a fort on a hill and a city grown up beneath it. The distances between them are the point — the desert changes colour twice a day and the road is where you see it.',
     'Jaipur, Jodhpur, Udaipur and Jaisalmer form the standard circuit. Bundi, Shekhawati and Bikaner are where the people who came back go.'],
    'Everyone does the same four cities. Add one nobody mentions and the trip changes completely.','Arjun Rao · North India editor'),
  s('maharashtra','Maharashtra','State','West','Mumbai, Ajanta, Konkan coast','Nov – Feb','7 – 9','₹3,800','3 airports',
    ['Mumbai is the obvious entry, but the state behind it holds the Ajanta and Ellora caves, the Sahyadri hill forts and six hundred kilometres of Konkan coastline that almost nobody visits.',
     'The monsoon here is a destination in itself — the Western Ghats between June and September are a different country.'],
    'Leave Mumbai on the third day. The state starts where the suburbs stop.','Priya Menon · West India editor'),
  s('goa','Goa','State','West','Beaches, Portuguese quarters','Nov – Feb','4 – 6','₹3,200','1 airport',
    ['Two Goas: the beach strip everyone pictures, and the interior of Portuguese churches, spice plantations and Latin Quarter houses in Fontainhas that most visitors never reach.',
     'North is busy and cheap, south is quiet and expensive, and the difference is roughly forty minutes of driving.'],
    'Stay inland one night. It costs less and you finally hear the birds.','Priya Menon · West India editor'),
  s('kerala','Kerala','State','South','Backwaters, Munnar, Fort Kochi','Sep – Mar','8 – 10','₹3,600','4 airports',
    ['Backwaters at sea level, tea at fifteen hundred metres, and a coastline that has been trading with the world for two thousand years. Kerala is narrow enough to cross in a morning and varied enough to fill a fortnight.',
     'The state has India\u2019s highest literacy and its most organised tourism, which shows in how easy independent travel is here.'],
    'Skip the private houseboat. The public ferry from Alappuzha costs ₹40 and goes the same way.','Meera Joshi · South India editor'),
  s('tamil-nadu','Tamil Nadu','State','South','Madurai, Ooty, Mahabalipuram','Nov – Feb','9 – 12','₹3,200','4 airports',
    ['The temple state — gopurams the height of office blocks, still in daily use after eight hundred years. Madurai, Thanjavur, Chidambaram and Srirangam are the four that justify the trip.',
     'The Nilgiris provide the relief: Ooty and Kodaikanal sit two thousand metres above the plains, reachable by a mountain railway that has run since 1908.'],
    'Go to one temple at 5am. It is a different building when it is working rather than being visited.','Meera Joshi · South India editor'),
  s('karnataka','Karnataka','State','South','Hampi, Coorg, Mysuru','Oct – Feb','8 – 10','₹3,400','3 airports',
    ['Hampi alone justifies the state — fourteen square miles of boulder-strewn ruins that was the richest city in the world in 1500. Add the Mysuru palace, the Coorg coffee hills and a long undeveloped coastline.',
     'Bengaluru is the entry point and worth two days for the food, though the traffic is genuinely as bad as reported.'],
    'Hampi needs three days, not one. The far side of the river is the half people miss.','Devang Patel · Heritage editor'),
  s('telangana','Telangana','State','South','Hyderabad, Ramoji, Warangal','Oct – Feb','4 – 6','₹3,000','1 airport',
    ['Hyderabad is the reason to come — Golconda, the Charminar, the Chowmahalla Palace and a biryani tradition that people fly in for.',
     'Warangal and the Ramappa temple, a UNESCO site since 2021, are a comfortable day trip from the city.'],
    'Eat the biryani where the queue is, not where the review said.','Arjun Rao · North India editor'),
  s('andhra-pradesh','Andhra Pradesh','State','South','Tirupati, Araku, Vizag','Oct – Mar','5 – 7','₹2,800','2 airports',
    ['Tirupati draws more pilgrims than anywhere else on earth, but the state also has the Araku valley railway, the Borra caves and a long stretch of quiet Bay of Bengal coast at Visakhapatnam.',
     'Vijayawada and Amaravati carry the Buddhist history most visitors do not expect.'],
    'The Araku train out of Visakhapatnam is the best five hours of rail in south India.','Meera Joshi · South India editor'),
  s('puducherry','Puducherry','UT','South','French quarter, Auroville','Nov – Feb','2 – 3','₹3,000','1 airport',
    ['A French colonial grid on the Coromandel coast, with yellow-walled streets, a seafront promenade closed to traffic each evening, and Auroville ten kilometres inland.',
     'Small enough to walk, and best treated as a slow two days rather than a stop.'],
    'The promenade closes to cars at six. That hour is the whole town at its best.','Meera Joshi · South India editor'),
  s('himachal-pradesh','Himachal Pradesh','State','North','Shimla, Manali, Spiti','Mar – Jun, Sep – Nov','7 – 12','₹2,800','2 airports',
    ['Two distinct halves: the green, accessible lower Himalaya of Shimla, Dharamshala and Manali, and the high desert of Spiti and Lahaul behind the passes.',
     'Spiti is only reachable between June and September. Planning around that single fact decides the whole trip.'],
    'Spiti is not an extension of Manali. Give it its own week or do not go.','Arjun Rao · North India editor'),
  s('uttarakhand','Uttarakhand','State','North','Rishikesh, Nainital, Char Dham','Mar – Jun, Sep – Nov','7 – 10','₹2,900','1 airport',
    ['The Ganga leaves the mountains at Rishikesh, and above it sit the four Char Dham shrines, Valley of Flowers and Corbett, India\u2019s oldest national park.',
     'Yoga and rafting have made Rishikesh famous; the state\u2019s high meadows are the better reason to come.'],
    'Valley of Flowers has a six-week window. Everything else can wait.','Nisha Thakkar · Mountains editor'),
  s('punjab','Punjab','State','North','Amritsar and the Golden Temple','Oct – Mar','3 – 4','₹2,600','1 airport',
    ['Amritsar carries the Golden Temple, open all night and serving free food to fifty thousand people a day, plus the Partition Museum and the Wagah border ceremony.',
     'The countryside between Amritsar and Chandigarh is flat, green and full of dhabas that do one thing exceptionally well.'],
    'Go to the Golden Temple at four in the morning. You will not forget it.','Arjun Rao · North India editor'),
  s('ladakh','Ladakh','UT','North','High-altitude desert, Pangong Tso','Jun – Sep','8 – 12','₹4,200','1 airport',
    ['A cold desert at three and a half thousand metres, with Tibetan Buddhist monasteries on ridgelines and lakes that change colour through the day.',
     'Altitude is the planning constraint: two days acclimatising in Leh before anything else, without exception.'],
    'Two days doing nothing in Leh is not wasted time. It is the trip working.','Nisha Thakkar · Mountains editor'),
  s('jammu-kashmir','Jammu & Kashmir','UT','North','Dal Lake, Gulmarg, Pahalgam','Apr – Oct','6 – 8','₹3,400','2 airports',
    ['Srinagar sits on a lake with houseboats that have not changed in a century, ringed by meadows at Gulmarg, Pahalgam and Sonamarg.',
     'Check current advisories before booking. Conditions vary by district and change.'],
    'A shikara at dawn on Dal Lake, before the market boats. That is the memory.','Nisha Thakkar · Mountains editor'),
  s('delhi','Delhi','UT','North','Capital, Mughal monuments','Oct – Mar','3 – 4','₹3,200','1 airport',
    ['Eight cities built on the same ground. Mughal Delhi around the Red Fort and Jama Masjid, colonial Delhi in Lutyens\u2019 avenues, and the tombs of Mehrauli older than both.',
     'The metro is excellent and makes the distances manageable in a way taxis do not.'],
    'Humayun\u2019s Tomb at opening is empty. The Taj gets the crowds; this gets the light.','Devang Patel · Heritage editor'),
  s('haryana','Haryana','State','North','Kurukshetra, Sultanpur, Morni','Oct – Mar','2 – 3','₹2,400','1 airport',
    ['Mostly passed through on the way to somewhere else, which is a shame — Kurukshetra carries the Mahabharata sites and Sultanpur is a serious birding lake an hour from Delhi.',
     'Morni Hills gives the state its only hill station, modest but genuinely quiet.'],
    'Sultanpur in January, at seven in the morning, is as good as birding gets near a capital.','Priya Menon · West India editor'),
  s('uttar-pradesh','Uttar Pradesh','State','Central','Taj Mahal, Varanasi, Ayodhya','Oct – Mar','8 – 12','₹2,700','3 airports',
    ['The Taj is here, and so is Varanasi, and between them sit Fatehpur Sikri, Sarnath, Lucknow\u2019s Awadhi kitchens and the ghats at Chitrakoot.',
     'It is the most-visited state in India and still the one where a day\u2019s drive finds something nobody photographs.'],
    'Varanasi at 5am from a boat. Everything else in the state is a supporting act.','Devang Patel · Heritage editor'),
  s('madhya-pradesh','Madhya Pradesh','State','Central','Khajuraho, Bandhavgarh, Orchha','Oct – Mar','8 – 11','₹3,000','3 airports',
    ['The best tiger reserves in India — Bandhavgarh, Kanha, Pench — plus Khajuraho, Sanchi and the riverside temples of Orchha and Maheshwar.',
     'Distances are large and the roads are better than expected. A driver for the week is the normal approach.'],
    'Two safaris a day for three days. One is a lottery; six is a reasonable chance.','Nisha Thakkar · Wildlife editor'),
  s('chhattisgarh','Chhattisgarh','State','Central','Chitrakote falls, Bastar','Oct – Mar','5 – 7','₹2,400','1 airport',
    ['Chitrakote, India\u2019s widest waterfall, and the Bastar region\u2019s weekly tribal markets, which remain one of the least-packaged experiences in the country.',
     'Infrastructure is thin. Go with a local operator or be comfortable improvising.'],
    'The Bastar haats are the reason to come, and they only happen on their own day.','Devang Patel · Heritage editor'),
  s('west-bengal','West Bengal','State','East','Kolkata, Darjeeling, Sundarbans','Oct – Mar','7 – 10','₹2,900','2 airports',
    ['Kolkata for the colonial architecture, the food and the bookshops; Darjeeling for tea and the toy train; the Sundarbans for mangrove tiger country reachable only by boat.',
     'Durga Puja in autumn turns the whole city into an open-air exhibition and is worth planning a year around.'],
    'Kolkata is a walking city disguised as a traffic jam. Start at College Street.','Meera Joshi · East India editor'),
  s('odisha','Odisha','State','East','Puri, Konark, Chilika','Oct – Mar','6 – 8','₹2,500','1 airport',
    ['The Sun Temple at Konark, the Jagannath temple at Puri, and Chilika, Asia\u2019s largest brackish lagoon, full of migratory birds and a resident dolphin population.',
     'The Buddhist sites at Ratnagiri and Udayagiri are excellent and almost empty.'],
    'Konark deserves a guide. Without one it is a beautiful building you do not understand.','Devang Patel · Heritage editor'),
  s('bihar','Bihar','State','East','Bodh Gaya, Nalanda','Oct – Mar','4 – 6','₹2,200','1 airport',
    ['Bodh Gaya is where the Buddha reached enlightenment, and remains a working pilgrimage centre with monasteries built by a dozen countries.',
     'Nalanda, the ruined university, and Rajgir\u2019s hot springs complete a compact and historically dense circuit.'],
    'Bodh Gaya in December, when the monasteries are full and the winter teachings run.','Meera Joshi · East India editor'),
  s('jharkhand','Jharkhand','State','East','Betla, Netarhat, waterfalls','Oct – Mar','4 – 5','₹2,200','1 airport',
    ['Forest, plateau and waterfalls — Hundru, Dassam and Jonha are all within an hour of Ranchi, and Betla National Park holds elephants and the occasional tiger.',
     'Netarhat is the state\u2019s hill station and one of the quieter sunrises in eastern India.'],
    'Go just after the monsoon. The falls are running and the plateau is green.','Meera Joshi · East India editor'),
  s('sikkim','Sikkim','State','East','Gangtok, Kanchenjunga views','Mar – May, Oct – Dec','5 – 7','₹3,000','1 airport',
    ['India\u2019s first fully organic state, with Kanchenjunga visible from the capital on a clear morning and monasteries at Rumtek and Pemayangtse.',
     'North Sikkim needs a permit arranged in advance and is worth the paperwork.'],
    'Clear mornings in October and November. That is when the mountain shows itself.','Nisha Thakkar · Mountains editor'),
  s('assam','Assam','State','North-East','Kaziranga, Majuli, tea gardens','Nov – Apr','5 – 7','₹2,800','2 airports',
    ['Kaziranga holds two thirds of the world\u2019s one-horned rhinos. Majuli is the largest river island in the world, with Vaishnavite monasteries that have been there for five centuries.',
     'The Brahmaputra defines the state, and a night on it is the best way to understand why.'],
    'Kaziranga on elephant-back at dawn, then the same park by jeep at four. Both, not either.','Nisha Thakkar · Wildlife editor'),
  s('meghalaya','Meghalaya','State','North-East','Cherrapunji, living root bridges','Oct – Apr','5 – 6','₹2,900','1 airport',
    ['The wettest place on earth, with living root bridges grown from ficus over decades and caves that run for kilometres under the plateau.',
     'The double-decker root bridge at Nongriat is a three-thousand-step descent and worth every one.'],
    'Stay a night at Nongriat. The day-trippers leave and the valley is yours.','Nisha Thakkar · Mountains editor'),
  s('arunachal-pradesh','Arunachal Pradesh','State','North-East','Tawang, Ziro valley','Oct – Apr','7 – 10','₹3,200','1 airport',
    ['Tawang holds the largest monastery in India outside Tibet, at three thousand metres and reached over the Sela Pass.',
     'The Ziro valley, with its Apatani villages and September music festival, is the other reason to come.'],
    'The road to Tawang is the destination. Give it two days each way.','Nisha Thakkar · Mountains editor'),
  s('nagaland','Nagaland','State','North-East','Hornbill festival, Khonoma','Oct – Apr','5 – 7','₹2,800','1 airport',
    ['The Hornbill Festival in the first week of December brings all sixteen tribes to Kisama, and is the single best week to visit.',
     'Khonoma, the green village, has banned hunting and rebuilt itself around conservation tourism.'],
    'Hornbill is extraordinary and completely booked. Reserve in August.','Meera Joshi · East India editor'),
  s('manipur','Manipur','State','North-East','Loktak Lake, Imphal','Oct – Mar','4 – 6','₹2,600','1 airport',
    ['Loktak Lake carries the world\u2019s only floating national park, where the phumdi islands support a population of endangered brow-antlered deer.',
     'Imphal\u2019s Ima Keithel is a market of five thousand stalls run entirely by women.'],
    'Ima Keithel at nine in the morning. There is nothing else like it in India.','Meera Joshi · East India editor'),
  s('mizoram','Mizoram','State','North-East','Aizawl, Phawngpui','Oct – Mar','4 – 5','₹2,600','1 airport',
    ['Ridge-top villages, near-total literacy and Phawngpui, the blue mountain, on the Myanmar border.',
     'Sunday is genuinely observed — plan travel around it.'],
    'Aizawl is built along a ridge. Walk it once end to end to understand the place.','Meera Joshi · East India editor'),
  s('tripura','Tripura','State','North-East','Ujjayanta Palace, Unakoti','Oct – Mar','3 – 5','₹2,400','1 airport',
    ['Unakoti\u2019s rock-cut reliefs are carved into a hillside and largely unvisited; Neermahal sits in the middle of a lake.',
     'Agartala is compact and the palace museum is better than its reputation.'],
    'Unakoti during the April festival, or completely alone in December. Both work.','Devang Patel · Heritage editor'),
  s('andaman-nicobar','Andaman & Nicobar','UT','South','Havelock, Neil, diving','Nov – Apr','6 – 8','₹4,500','1 airport',
    ['The best diving in India, off Havelock and Neil, with visibility that holds through the dry season and a marine park at Wandoor.',
     'Ferries book out weeks ahead in season — that, not flights, is the bottleneck.'],
    'Book the inter-island ferries before the hotel. They sell out first.','Meera Joshi · South India editor'),
  s('lakshadweep','Lakshadweep','UT','South','Atolls, lagoons','Oct – Mar','4 – 6','₹5,000','1 airport',
    ['Thirty-six coral islands, ten inhabited, with permits required and visitor numbers deliberately capped.',
     'Agatti and Bangaram take most visitors; the lagoon water is the clearest in the country.'],
    'Permits take weeks. Start the paperwork before you dream about the water.','Meera Joshi · South India editor'),
  s('chandigarh','Chandigarh','UT','North','Le Corbusier city, Rock Garden','Oct – Mar','2','₹2,800','1 airport',
    ['Le Corbusier\u2019s planned capital, with the Capitol Complex a UNESCO site and Nek Chand\u2019s Rock Garden built secretly from industrial waste over eighteen years.',
     'Flat, walkable and easy — a genuine two-day city.'],
    'The Capitol Complex needs a free permit and a guide. Arrange it the day before.','Devang Patel · Heritage editor'),
];

export const STATE_BY_SLUG = new Map(STATES.map((x) => [x.slug, x]));
export const REGION_ORDER: Region[] = ['North','West','South','East','North-East','Central'];
